aproject/urls.py
from django.urls import path
from . import views

app_name = "aproject"

urlpatterns = [

    path("index/", views.index, name="index"),
    path("show/<ipk>", views.show, name="show"),
    path("create/", views.create, name="create"),
    path("delete/<ipk>", views.delete, name="delete"),
    path("update/<ipk>", views.update, name="update"),





]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('index/', views.index , name='index'),
    path('signin/', views.signin_user, name='signin'),
    path('singout/', views.singout_user, name='signout'),
    path('signup/', views.signup, name='signup'),
    path("profile/",views.profile, name ="profile"),
    path("update/",views.update, name ="update"),
    path("delete/",views.delete, name ="delete")


]

popol/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index),
    path('main/', include('main.urls')),
    path('aproject/',include('aproject.urls')),
    path('bproject/',include('bproject.urls')),
    path('cproject/',include('cproject.urls')),
    path('apopol/',include('apopol.urls')),
    path('bpopol/',include('bpopol.urls')),
    path('cpopol/',include('cpopol.urls')),
    path('dpopol/',include('dpopol.urls')),
    path('coverletter/',include('coverletter.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aproject/models.py
from django.db import models
from main.models import User
# Create your models here.


class Project(models.Model):
    project = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker", null=True, blank=True) 
    content = models.TextField(null=True, blank=True)
    tech = models.TextField(null=True, blank=True)
    pubdate = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.project
    

class Image(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to="aproject/%y/%m", null=True, blank=True)
    con = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.project}_{self.con}"

aproject/views.py
from django.shortcuts import render,redirect
from .models import Project,Image
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages



def index(req):
    pg = req.GET.get("page", 1)
    p = Project.objects.all()

    cate = req.GET.get("cate","")
    ss = req.GET.get("ss","")

    if ss:
        if cate =="pro":
            p = Project.objects.filter(project__startswith=ss)
        elif cate == "mak":
            try:
                from main.models import User
                u = User.objects.get(username=ss)
                p = Project.objects.filter(maker=u)
            except:
                p = Project.objects.none() #아무것도 없는 레코드 설정시 적용
                

        elif cate =="con":
            p = Project.objects.filter(content__contains=ss)
        else:
            p = Project.objects.all()
    else:
        p = Project.objects.all()

    p = p.order_by('-pubdate')

    pag =Paginator(p,11)
    obj = pag.get_page(pg)
    
    context = {
        "pset" :obj,
        "ss" : ss,
        "cate": cate
    }

    return render(req, "aproject/index.html",context)

def show(req,ipk):
    project = Project.objects.get(id=ipk)
    ph = project.image_set.all()
    context = {
        "pro" : project,
        "phset" : ph
    }

    return render(req,"aproject/show.html",context)

def create(req):
    if req.method == "POST":
        pro = req.POST.get("pro")
        c = req.POST.get("con")
        t = req.POST.get("tech")
        cp = req.FILES.getlist("cpic")
        cc = req.POST.getlist("ccon")
        p = Project(project=pro, content=c, tech=t, maker=req.user, pubdate=timezone.now())
        p.save()
        for pic, con in zip(cp,cc):
            Image(project=p, pic=pic, con=con).save()
        
        return redirect("aproject:index")       
    return render(req, "aproject/create.html")

def delete(req,ipk):
    project = Project.objects.get(id=ipk)
    if project.maker == req.user:
        project.delete()
    else:
        messages.error(req, "작성자가 아니면 삭제 할 수 없습니다.")
    return redirect("aproject:index")

def update(req,ipk):
    project = Project.objects.get(id=ipk)
    ph = Image.objects.filter(project=project)

    if project.maker != req.user:        # 글작성자와 업데이트 작성자가 같지 않다면
        messages.error(req,"작성자가 아니면 수정 할 수 없습니다.")
        return redirect("aproject:index")

    if req.method == "POST":
        pro = req.POST.get("pro")
        c = req.POST.get("con")        
        project.project = pro
        project.content = c
        project.save()
        return redirect("aproject:index")
    context = {

        "pro" : project,
        "phset" : ph

    }
    return render(req,"aproject/update.html",context)

# Create your views here.

templates/aproject/create.html
{% extends 'base.html' %}

{% block super %}

<div class ="container-fluid a" style="color: white;">
    <!-- <div style="padding-top: 75px; padding-left: 135px;">
        <h1><b>Create Project</b></h1>
    </div><br> -->

    <div class="container" style="padding-top:75px;">
        <h1><b>Create Project</b></h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}  
                <div class="mb-3 mt-3" style="padding-top: 25px;">
                    <label class="form-label">WRITER</label>
                    <input type="text" class="form-control" value="{{ user }}" style="width:fit-content"  disabled>
                </div>

                <div class="mb-3">
                    <label class="form-label">SUBJECT</label>
                    <input type="text" class="form-control"  name ="pro" placeholder="제목 입력">
                </div>

                <div class="mb-3">
                    <label class="form-label">Using Tech</label>
                    <input type="text" class="form-control"  name ="tech" placeholder="사용 기술 입력">
                </div>

                <div class="mb-3">
                    <label class="form-label">CONTENT</label>
                    <textarea class="form-control" style="resize : none; height: 300px;" name ="con" placeholder="내용 입력" style="height: 150px;"></textarea>
                </div>

                <div class="text-end mt-4">
                    <button class="btn btn-outline-light" type="button" onclick="makesel()">Image ADD</button>
                    <button class="btn btn-outline-light">Project Upload</button>
                </div>
                <div id="here" class="row mt-5">

                </div>
            </div>
        </form>
    </div>
</div>
<script>
    function makesel(){
        d = document.getElementById("here");
        n = document.createElement("div");
        n.setAttribute("class", "col-lg-4 mt-5");
        n.innerHTML = '<input type="file" name="cpic" class="form-control mt-3 mb-3">\
        <textarea placeholder="보기설명" name="ccon" class="form-control"></textarea>';
        d.appendChild(n);
    }
</script>

{% endblock%}

templates/aproject/index.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block con %}

<div class ="container" style="color: white; padding-top: 50px;">
  
    

    <div style="padding-top: 15px;">
        <!-- 제목 -->
            <div class="card mb-3" style="max-width: auto; height: auto; background-color:transparent;">
                <div class="row g-0">
                <div class="col-md-4">
                    <img src="/static/base/project/network.jpg" class="img-fluid rounded-start" alt="..." style="width: 95%; height: 100%;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                    <h1 class="card-title">Network Project</h1>
                    <hr class="opacity-100" style="background-color: rgb(9, 48, 59);">
                    <p class="card-text">GNS를 이용한 Enterprise Network 구성</p>
                    <div class="text-end">
                        {% if user.is_superuser %}
                        <a href = "{% url 'aproject:create' %}"><button class="btn btn-outline-light">Create</button></a>
                        {% endif %}
                    </div>
                    </div>
                </div>
                </div>
            </div>
        <!-- 게시글 -->
            <table class="table mt-3 table-borderless">
                <thead style="color: white;">
                    <tr>
                        <th scope="col" width=5%>No</th>
                        <th scope="col" width=25%>Projcet</th>
                        <th scope="col" width=60%>Content</th>
                        <th scope="col" width=10%>Maker</th>
                    
                    </tr>
                </thead>
                <tbody style="color: white;">
                    {% if pset %}
                        {% for i in pset %}
                            <tr>
                                <th scope="row">{{ pset.start_index|add:forloop.counter0}}</th>
                                <td>{{i.project}}</td>
                                <td><a href="{% url 'aproject:show' i.id %}">{{i.content}}</a></td>
                                <td>{{i.maker}}</td>
                            </tr>
                        {% endfor %}
                    {% else %}

                        <tr>
                        {% if ss %}
                            <th colspan="5" class="text-center">
                                <b>검색결과가 없습니다</b>
                            </th>
                        {% else %}
                            <th colspan="5" class="text-center">
                                <b>게시글이 없습니다</b>
                            </th>
                        {% endif %}
                        
                        </tr>
                    {% endif %}
                </tbody>
            </table>
                    <!-- 페이징 기능 -->

                    <nav aria-label="Page navigation example" class="mt-5">
                        <ul class="pagination justify-content-center">
                            {% if pset.has_previous %}
                                <li class="page-item">                   
                                    <a class="page-link" href="{% url 'aproject:index' %}?page=1&ss={{ss}}&cate={{cate}}">Home</a>
                                </li>
                                <li class="page-item">                   
                                    <a class="page-link" href="{% url 'aproject:index' %}?page={{ pset.previous_page_number }}&ss={{ss}}&cate={{cate}}">이전</a>
                                </li>        
                            {% else %}                    
                            <li class="page-item disabled">
                                <a class="page-link">Home</a>
                            </li>
                            <li class="page-item disabled">
                                <a class="page-link">이전</a>
                            </li>                      
                            {% endif %}
                            
            
                            {% for i in pset.paginator.page_range %}
                                {% if i >= pset.number|sub:5 and pset.number|add:4 >= i %}
                                    <li class="page-item {% if i == pset.number%} active {% endif %}"><a class="page-link" href="{% url 'aproject:index' %}?page={{i}}&ss={{ss}}&cate={{cate}}">{{i}}</a></li>
                                {% endif %}
                            {% endfor %}
                            
                            {% if pset.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'aproject:index' %}?page={{ pset.next_page_number }}&ss={{ss}}&cate={{cate}}">다음</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'aproject:index' %}?page={{ pset.paginator.num_pages }}&ss={{ss}}&cate={{cate}}">마지막</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link">다음</a>
                                </li>
                                <li class="page-item disabled">
                                    <a class="page-link">마지막</a>
                                </li>
                            {% endif %}
            
                        </ul>
                    </nav>
                
                    <br><br>
                        <form>
                            <div class="row mb-5 mt-4 justify-content-center"> 
                                <div class="col-lg-2 text-end">           
                                        <select class="form-select mb-3" name ="cate" aria-label=".form-select-lg example">
                                            <option value="pro" {% if cate == "pro"%} selected {% endif %}>제목</option>
                                            <option value="mak" {% if cate == "mak"%} selected {% endif %}>작성자</option>
                                            <option value="con" {% if cate == "con"%} selected {% endif %}>내용</option>
                                        </select>                        
                                </div>
            
                                <div class="col-lg-8 text-end">
                                    <input type ="text" name="ss" class="form-control" value="{{ss}}">
                                    <br>
                                </div>
            
                                <div class="col-lg-2">                    
                                    <button class="btn btn-outline-light">검색</button>
                                    <a href="{% url 'aproject:index' %}" class="btn btn-outline-light">Home</a>                    
                                </div>
                            </div>
                        </form>  
    </div>
</div>


{% endblock %}

templates/aproject/show.html
{% extends 'base.html' %}

{% block con %}

<div class ="container-fluid a" style="color: white;">
    <div class="text-center" style="padding-top: 75px;">
        <h1><b>{{pro.project}}</b></h1><br>
    </div>

    <div class="row" style="width: 100%;">
        <div class="col-lg-4 text-center" style="display: flex;"> 
            <div style="padding-left: 30px;">  
                <hr>
                <b>Use Technology  : {{pro.tech}}</b><br>
                <hr>
                {% for i in phset %}
                <div class="col-lg-6" style="width: 100%; height: auto;">
                    <div class="text-end">
                        <h5>{{ i.con }}</h5>
                    </div>
                    <!-- <a href="{{ i.pic.url }}" class="text-decoration-none text-muted" role="button" download> -->
                    <img src="{{ i.pic.url }}" width="100%; height: 50%;"><hr>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-lg-8 text-center" style="padding-top:15px; padding-left: 45px;">
                <img src="{{ pro.maker.getpic }}" width="10%"> 
                <h5>{{ pro.maker }}</h5>
                <b>작성일 : </b>{{pro.pubdate | date:'Y년 n월 j일 H:i' }}<br><br>
            
                <a href = "/aproject/index"><button class ="btn btn-outline-light">목록</button></a>
                {% if user.is_superuser %}
                    <a href ="{% url 'aproject:update' pro.id %}"><button type="button" class="btn btn-outline-light">Edit</button></a>
                    <a href = "{% url 'aproject:delete' pro.id %}"><button type="button" class="btn btn-outline-danger">Del</button></a>
                {% endif %}
                <br><br>
                <textarea class="form-control"  disabled style="resize : none; width : 100%; height : 65%;">{{ pro.content }}</textarea>
        </div>   
    </div> 
</div>

{% endblock%}





 

templates/aproject/update.html
{% extends 'base.html' %}

{% block super %}

<div class ="container-fluid a" style="color: white;">

    <div class="container-fluid" style="padding-top: 50px;">
        <h1><b>Update Page</b></h1><br>
        <form method="POST" >
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-2 text-center" style="padding-top: 20px;">
                    <button class="btn btn-outline-light">Update</button>
                    <a href ="{% url 'aproject:show' pro.id %}"><button type="button" class="btn btn-outline-light">뒤로가기</button></a>
                    <br><br>
              
                
                </div>
            

                <div class="col-lg-10">
                    <label class="form-label">제목 수정</label><br>
                    <input class="form-control"  style="width: 300px;" placeholder="project" name="pro" value="{{pro.project}}"><br>
                    <label class="form-label">내용 수정</label><br>
                    <textarea class="form-control"  style="height : 550px; width: 100%;" name ="con">{{pro.content}}</textarea>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock%}