apopol/urls.py
from django.urls import path
from . import views

app_name = "apopol"

urlpatterns = [

    # path("index/", views.index, name="index"),
    # path("index/upload/",views.upload, name="upload"),

    path("index/", views.PortListView.as_view(), name="index"),
    path("index/upload/", views.UploadPortView.as_view(), name="upload"),
    path("delete/<pk>", views.delete, name="delete")
]

bpopol/urls.py
from django.urls import path
from . import views

app_name = "bpopol"

urlpatterns = [


    path("index/", views.PortListView.as_view(), name="index"),
    path("index/upload/", views.UploadPortView.as_view(), name="upload"),
    path("delete/<pk>", views.delete, name="delete")
]

cpopol/urls.py
from django.urls import path
from . import views

app_name = "cpopol"

urlpatterns = [


    path("index/", views.PortListView.as_view(), name="index"),
    path("index/upload/", views.UploadPortView.as_view(), name="upload"),
    path("delete/<pk>", views.delete, name="delete")
]

dpopol/urls.py
from django.urls import path
from . import views

app_name = "dpopol"

urlpatterns = [


    path("index/", views.PortListView.as_view(), name="index"),
    path("index/upload/", views.UploadPortView.as_view(), name="upload"),
    path("delete/<pk>", views.delete, name="delete")
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('index/', views.index , name='index'),
    path('signin/', views.signin_user, name='signin'),
    path('singout/', views.singout_user, name='signout'),
    path('signup/', views.signup, name='signup'),
    path("profile/",views.profile, name ="profile"),
    path("update/",views.update, name ="update"),
    path("delete/",views.delete, name ="delete")


]

popol/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index),
    path('main/', include('main.urls')),
    path('aproject/',include('aproject.urls')),
    path('bproject/',include('bproject.urls')),
    path('cproject/',include('cproject.urls')),
    path('apopol/',include('apopol.urls')),
    path('bpopol/',include('bpopol.urls')),
    path('cpopol/',include('cpopol.urls')),
    path('dpopol/',include('dpopol.urls')),
    path('coverletter/',include('coverletter.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    {% load static %}
    <title>Hoon's Site</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/navbars-offcanvas/">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/collepse.css" rel="stylesheet">
    <link href="/static/css/style2.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,0,0" />

  </head>

  <body>
    
    <main>
        <!-- Navbar Area -->
        <nav class="navbar navbar-dark bg-dark" aria-label="Dark offcanvas navbar">
            <div class="container-fluid">

                <a class="navbar-brand" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark" aria-controls="offcanvasNavbarDark"><span class="material-symbols-outlined">
                    menu
                    </span></a>
             
                <div class="offcanvas offcanvas-start text-bg-dark" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasNavbarDark" aria-labelledby="offcanvasNavbarDarkLabel" style="width: 200px;">
                    
                    <!-- offcanvas header 부분 (홈으로 이동) -->
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel"><a href="{% url 'main:index' %}" style="text-decoration:none; color: white; font-weight: bolder;">Main</a></h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    
                    <!-- offcancas body 부분 (프로젝트, 포트폴리오 목록 등등) -->
                    <div class="offcanvas-body">
                        <ul class="list-unstyled ps-0">
                            <li class="mb-1">
                              <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
                                Project
                              </button>
                              <div class="collapse show" id="home-collapse">
                                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                  <li><a href="{% url 'aproject:index' %}" class="link-light d-inline-flex text-decoration-none rounded">Network</a></li>
                                  <li><a href="{% url 'bproject:index' %}" class="link-light d-inline-flex text-decoration-none rounded">Web Page</a></li>
                                  <li><a href="{% url 'cproject:index' %}" class="link-light d-inline-flex text-decoration-none rounded">AWS</a></li>
                                </ul>
                              </div>
                            </li>
                            <li class="mb-1">
                              <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
                                Portfolio
                              </button>
                              <div class="collapse show" id="dashboard-collapse">
                                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                  <li><a href="{% url 'apopol:index' %}" class="link-light d-inline-flex text-decoration-none rounded">Network</a></li>
                                  <li><a href="{% url 'bpopol:index' %}" class="link-light d-inline-flex text-decoration-none rounded">Web Page</a></li>
                                  <li><a href="{% url 'cpopol:index' %}" class="link-light d-inline-flex text-decoration-none rounded">AWS</a></li>
                                  <li><a href="{% url 'dpopol:index' %}" class="link-light d-inline-flex text-decoration-none rounded">Server</a></li>
                                  <!-- <li><a href="#" class="link-light d-inline-flex text-decoration-none rounded">Docker & Kuber</a></li> -->
                                </ul>
                              </div>
                            </li>
                            <li class="mb-1">
                              <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
                                About
                              </button>
                              <div class="collapse" id="orders-collapse">
                                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                  <li><a href="{% url 'coverletter:index' %}" class="link-light d-inline-flex text-decoration-none rounded">Cover letter</a></li>
                                </ul>
                              </div>
                            </li>
                          </ul>
                    </div>
                    


                    <!-- 인증된 회원 프로필 페이지 -->
                    <div class="offcanvas-footer">
                        {% if user.is_authenticated %}
                            <hr>
                            <div class="dropup" style="padding-left: 15px;">
                                <a href="#" class="d-flex align-items-center text-white text-decoration-none" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="material-symbols-outlined" style="padding-right: 15px;">
                                        login
                                        </span><img src="{{ user.getpic }}" alt="" width="32" height="32" class="rounded-circle me-2"> 
                                    <strong>{{ user }}<span class="material-symbols-outlined" style="font-size: 12px; padding-left: 3px;">
                                        add
                                        </span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-lg-end dropdown-menu-dark">
                                    <li><a class="dropdown-item" href="{% url 'main:profile' %}">Profile</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'main:signout' %}">Sign out</a></li>
                                </ul>
                            </div>
                            {% else %}
                            {% endif %}
                    </div>
                </div>


                <!-- 인증되지 않은 회원 페이지 -->
                {% if user.is_authenticated %}
                {% else %}
                    <div class="navbar-brand">
                        <a href="{% url 'main:signin' %}"><button type="button" class="btn btn-outline-light" style="width: fit-content; font-size: 15px;">SignIn</button></a>
                        <a href="{% url 'main:signup' %}"><button type="button" class="btn btn-outline-light" style="width: fit-content; font-size: 15px;">SignUp</button></a>
                    </div>

                {% endif %}
            </div>
        </nav>
    </main>

    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/swiper@6.8.4/swiper-bundle.min.js"></script>
    
    {% for i in messages %}
    <div class="alert {{ i.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ i.tags | upper }}</strong> {{ i.message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
     
    {% endfor %}
     
  </body>


        {% block con %}
        {% endblock %}
  

    
    {% if user.is_superuser %}

        {% block super %}
        {% endblock %}

    {% endif %}

</html>